Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace final_qualifying_work.Models
{
    public class Project
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public required string Title { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }

        public ICollection<ProjectTask> Tasks { get; set; }
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace final_qualifying_work.Models
{
    public class User
    {
        public int Id { get; set; }

        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Email { get; set; }

    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace final_qualifying_work.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UsersController.cs
using final_qualifying_work.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace final_qualifying_work.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class UsersController : ControllerBase
    {
        private readonly AppDbContext _context;

        public UsersController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetUsers()
        {
            var users = _context.Users.ToList();
            return Ok(users);
        }
    }
}

Pages/User/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace final_qualifying_work.Pages.User
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            Response.Cookies.Delete("jwt");
            return RedirectToPage("/Login");
        }
        public IActionResult OnPost()
        {
            Response.Cookies.Delete("jwt");
            return RedirectToPage("/Login");
        }
    }
}

Pages/User/Privacy.cshtml.cs
using final_qualifying_work.Data;
using final_qualifying_work.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace final_qualifying_work.Pages.User
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly AppDbContext _context;

        public PrivacyModel(AppDbContext context)
        {
            _context = context;
        }

        public void OnGet()
        {

        }
    }

}

Pages/User/Projects.cshtml.cs
using final_qualifying_work.Models;
using final_qualifying_work.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Security.Principal;
using Task = System.Threading.Tasks.Task;

namespace final_qualifying_work.Pages.User
{
    [Authorize]
    public class ProjectsModel : PageModel
    {
        private readonly ProjectService _projectRepository;
        private readonly ILogService _logService;
        private readonly IProjectUserRepository _projectUserRepository;
        private readonly IWebHostEnvironment _environment;
        private readonly JwtService _jwtService;

        public ProjectsModel(ProjectService projectRepository, IWebHostEnvironment environment, IProjectUserRepository projectUserRepository, ILogService logService, JwtService jwtService)
        {
            _projectRepository = projectRepository;
            _environment = environment;
            _projectUserRepository = projectUserRepository;
            _logService = logService;
            _jwtService = jwtService;
        }

        public IEnumerable<Project> Projects { get; set; }

        public async Task OnGetAsync()
        {
            Projects = await _projectRepository.GetAllPublishedProjectsAsync();
        }

        public async Task<IActionResult> OnPostCreateAsync(
            string Title,
            string Description)
        {
            try
            {
                var project = new Project
                {
                    Title = Title,
                    Description = Description,
                    CreatedDate = DateTime.Now
                };

                _projectRepository.AddProject(project);
                await _projectUserRepository.AddUserToProjectAsync(User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, project.Id, ProjectRole.Admin, true);
                await _logService.AddLog(project.Id, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.CreateProject, project.Title);

                ProjectUser ap = await _projectUserRepository.GetProjectUserAsync(project.Id, int.Parse(User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value));
                string rule;
                switch (ap.Role)
                {
                    case ProjectRole.Watcher:
                        rule = "UserNone";
                        break;
                    case ProjectRole.User:
                        rule = "UserUser";
                        break;
                    case ProjectRole.Admin:
                        rule = "UserAdmin";
                        break;
                    default:
                        return LocalRedirect("/User/Projects");
                }

                var newToken = _jwtService.GenerateToken(ap.User, rule);

                Response.Cookies.Delete("jwt");
                Response.Cookies.Append("jwt", newToken.Token, new CookieOptions
                {
                    HttpOnly = true,
                    Secure = true,
                    SameSite = SameSiteMode.Strict,
                    Expires = newToken.Expires
                });

                return LocalRedirect("/User/Projects");
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, message = ex.Message });
            }
        }
    }
}

Pages/User/Tasks.cshtml.cs
using final_qualifying_work.Models;
using final_qualifying_work.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace final_qualifying_work.Pages.User
{
    [Authorize]
    public class TasksModel : PageModel
    {
        private readonly ITaskRepository _taskRepository;
        private readonly ProjectService _projectRepository;
        private readonly ILogService _logService;

        public TasksModel(ITaskRepository taskRepository, ProjectService projectRepository, ILogService logService)
        {
            _taskRepository = taskRepository;
            _projectRepository = projectRepository;
            _logService = logService;
        }

        public Project Project { get; set; }
        public List<ProjectTask> TodoTasks { get; set; } = new List<ProjectTask>();
        public List<ProjectTask> InProgressTasks { get; set; } = new List<ProjectTask>();
        public List<ProjectTask> DoneTasks { get; set; } = new List<ProjectTask>();

        public async Task<IActionResult> OnGetAsync(int projectId)
        {
            Project = await _projectRepository.GetProjectByIdAsync(projectId);
            if (Project == null)
            {
                return NotFound();
            }
            var allTasks = await _taskRepository.GetTasksByProjectAsync(projectId);

            TodoTasks = allTasks.Where(t => t.Status == Models.TaskStatus.ToDo).ToList();
            InProgressTasks = allTasks.Where(t => t.Status == Models.TaskStatus.InProgress).ToList();
            DoneTasks = allTasks.Where(t => t.Status == Models.TaskStatus.Done).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostMoveTaskAsync([FromBody] ProjectTask projectTask)
        {
            ProjectTask task = await _taskRepository.GetTaskByIdAsync(projectTask.Id);
            switch (projectTask.Status)
            {
                case Models.TaskStatus.ToDo or Models.TaskStatus.InProgress or Models.TaskStatus.Done:
                    await _logService.AddLog(projectTask.ProjectId, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.UpdateStatusTask, task.Title + " на " + projectTask.Status);
                    await _taskRepository.MoveTaskAsync(projectTask.Id, projectTask.Status);
                    break;
                case Models.TaskStatus.Delete:
                    await _logService.AddLog(projectTask.ProjectId, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.DeleteTask, task.Title);
                    await _taskRepository.DeleteTaskAsync(projectTask.Id);
                    break;
            }
            return new JsonResult(new { success = true });
        }

        public async Task<IActionResult> OnPostUpdateTaskAsync([FromBody] ProjectTask projectTask)
        {
            await _logService.AddLog(projectTask.ProjectId, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.UpdateTask, projectTask.Title);
            await _taskRepository.UpdateTaskAsync(projectTask);
            return new JsonResult(new { success = true });
        }

        public async Task<IActionResult> OnPostAddTaskAsync([FromBody] ProjectTask projectTask)
        {
            try
            {
                await _taskRepository.AddTaskAsync(projectTask);
                await _logService.AddLog(projectTask.ProjectId, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.CreateTask, projectTask.Title);
                return new JsonResult(new
                {
                    success = true,
                    taskId = projectTask.Id,
                    createdDate = projectTask.CreatedDate.ToString("g")
                });

            }catch (Exception ex)
            {
                return new JsonResult(new { success = false, message = ex.Message });
            }

        }
    }
}

Pages/User/Team.cshtml.cs
using final_qualifying_work.Models;
using final_qualifying_work.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace final_qualifying_work.Pages.User
{
    [Authorize(Roles = "UserAdmin")]
    public class TeamModel : PageModel
    {
        private readonly IProjectUserRepository _projectUserRepository;
        private readonly ProjectService _projectRepository;
        private readonly ILogService _logService;

        public TeamModel(IProjectUserRepository projectUserRepository, ProjectService projectRepository, ILogService logService)
        {
            _projectUserRepository = projectUserRepository;
            _projectRepository = projectRepository;
            _logService = logService;
        }

        public Project Project { get; set; }
        public List<ProjectUser> ProjectUsers { get; set; } = new List<ProjectUser>();

        public async Task<IActionResult> OnGetAsync(int projectId)
        {
            Project = await _projectRepository.GetProjectByIdAsync(projectId);
            if (Project == null)
            {
                return NotFound();
            }

            ProjectUsers = await _projectUserRepository.GetUsersByProjectAsync(projectId);
            return Page();
        }

        public async Task<IActionResult> OnPostUpdateRoleAsync([FromBody] UserModel model)
        {
            try
            {
                if (!Enum.TryParse(model.Role, out ProjectRole role))
                {
                    return new JsonResult(new { success = false, error = "Некорректная роль" });
                }

                await _projectUserRepository.UpdateUserRoleAsync(model.projectId, model.userId, role);
                return new JsonResult(new { success = true });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, error = ex.Message });
            }
        }

        public async Task<IActionResult> OnPostRemoveUserAsync([FromBody] UserModel model)
        {
            try
            {
                await _logService.AddLog(model.projectId, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.DeleteUser, (await _projectUserRepository.GetProjectUserAsync(model.projectId, model.userId)).User.Username);
                await _projectUserRepository.RemoveUserFromProjectAsync(model.projectId, model.userId);
                return new JsonResult(new { success = true });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, error = ex.Message });
            }
        }

        public async Task<IActionResult> OnPostAddUserAsync([FromBody] UserModel model)
        {
            try
            {
                if (!Enum.TryParse(model.Role, out ProjectRole projectRole))
                {
                    return new JsonResult(new { success = false, error = "Некорректная роль" });
                }

                var prUser = await _projectUserRepository.AddUserToProjectAsync(model.Email, model.projectId, projectRole);
                await _logService.AddLog(model.projectId, User.Claims.First(x => x.Type == ClaimValueTypes.Email).Value, LogProjectType.AddUser, prUser.User.Username);
                return new JsonResult(new { success = true });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, error = ex.Message });
            }
        }
    }
    public class UserModel
    {
        public int userId { get; set; }
        public int projectId { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    }
}

Pages/User/Logout.cshtml
@page
@model LogoutModel
@{
}

Pages/User/ProjectIndex.cshtml
@page
@model final_qualifying_work.Pages.User.ProjectIndexModel
@{
    ViewData["Title"] = "Чат проекта";
}

<div class="container-fluid chat-container">
    <div class="row">
        <!-- Список проектов -->
        <div class="col-md-3 projects-sidebar">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5>Мои проекты</h5>
                </div>
                <div class="card-body">
                    <div class="list-group">
                        @foreach (var project in Model.UserProjects)
                        {
                            <a href="?projectId=@project.Id" 
                               class="list-group-item list-group-item-action @(Model.CurrentProject?.Id == project.Id ? "active" : "")">
                                @project.Name
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>

        <!-- Область чата -->
        <div class="col-md-6 chat-area">
            @if (Model.CurrentProject != null)
            {
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <h5>Чат проекта: @Model.CurrentProject.Name</h5>
                    </div>
                    
                    <div class="card-body messages-container" id="messagesContainer">
                        @foreach (var message in Model.Messages)
                        {
                            <div class="message @(message.UserId == Model.CurrentUserId ? "sent" : "received")">
                                <div class="message-header">
                                    <strong>@message.Username</strong>
                                    <small class="text-muted">@message.SentAt.ToString("HH:mm dd.MM.yyyy")</small>
                                </div>
                                <div class="message-content">@message.MessageText</div>
                            </div>
                        }
                    </div>
                    
                    <div class="card-footer">
                        <form id="sendMessageForm" method="post">
                            <input type="hidden" name="projectId" value="@Model.CurrentProject.Id" />
                            <div class="input-group">
                                <input type="text" name="message" class="form-control" placeholder="Введите сообщение..." required />
                                <button type="submit" class="btn btn-primary">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div>
            }
            else
            {
                <div class="card">
                    <div class="card-body text-center">
                        <h5>Выберите проект для просмотра чата</h5>
                    </div>
                </div>
            }
        </div>

        <!-- Список участников проекта -->
        <div class="col-md-3 members-sidebar">
            @if (Model.CurrentProject != null)
            {
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h5>Участники проекта</h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            @foreach (var member in Model.ProjectMembers)
                            {
                                <div class="list-group-item">
                                    @member.Username
                                    @if (member.IsProjectOwner)
                                    {
                                        <span class="badge bg-success ms-2">Пользователь</span>
                                    }
                                </div>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>


<style>
    .chat-container {
        margin-top: 20px;
        height: 80vh;
    }
        
    .projects-sidebar, .members-sidebar, .chat-area {
        height: 100%;
        display: flex;
        flex-direction: column;
    }
        
    .messages-container {
        overflow-y: auto;
        height: 60vh;
        padding: 10px;
        background-color: #f8f9fa;
    }
        
    .message {
        margin-bottom: 15px;
        padding: 10px;
        border-radius: 5px;
        max-width: 80%;
    }
        
    .message.sent {
        background-color: #d1ecf1;
        margin-left: auto;
        border: 1px solid #bee5eb;
    }
        
    .message.received {
        background-color: #f8d7da;
        margin-right: auto;
        border: 1px solid #f5c6cb;
    }
        
    .message-header {
        display: flex;
        justify-content: space-between;
        margin-bottom: 5px;
        font-size: 0.9em;
    }
        
    .message-content {
        word-wrap: break-word;
    }
</style>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('projectsMainLink').classList.add('active');
            document.getElementById('projectDashboardLink').classList.add('active');
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.min.js"></script>
    <script>
        const connection = new signalR.HubConnectionBuilder()
            .withUrl("/projectChatHub")
            .configureLogging(signalR.LogLevel.Information)
            .build();

        connection.on("ReceiveProjectMessage", (projectId, userId, username, message, sentAt) => {
            if (projectId == @(Model.CurrentProject?.Id ?? 0)) {
                const isSent = userId == @Model.CurrentUserId;
                const messageClass = isSent ? 'sent' : 'received';
                const formattedTime = new Date(sentAt).toLocaleTimeString('ru-RU', {
                    hour: '2-digit',
                    minute: '2-digit',
                    day: '2-digit',
                    month: '2-digit',
                    year: 'numeric'
                }).replace(',', '');
                
                const messageHtml = `
                    <div class="message ${messageClass}">
                        <div class="message-header">
                            <strong>${username}</strong>
                            <small class="text-muted">${formattedTime}</small>
                        </div>
                        <div class="message-content">${message}</div>
                    </div>
                `;
                
                document.getElementById('messagesContainer').innerHTML += messageHtml;
                scrollToBottom();
            }
            console.log("Получено сообщение:", message); // Для отладки
        });

        async function startConnection() {
            try {
                await connection.start();
                console.log("SignalR Connected.");
                
                // Присоединяемся к группе проекта, если выбран
                @if (Model.CurrentProject != null)
                {
                    @:await connection.invoke("JoinProjectChat", @Model.CurrentProject.Id);
                }
            } catch (err) {
                console.log(err);
                setTimeout(startConnection, 5000);
            }
        }

        startConnection();

        document.getElementById('sendMessageForm')?.addEventListener('submit', function(e) {
            e.preventDefault();
            const form = e.target;
            const formData = new FormData(form);
            console.log(@Model.CurrentProject.Id);
            console.log(form.message.value);
            if (connection != null) {
                try
                {
                    connection.invoke("SendMessageToProject", @Model.CurrentProject.Id, form.message.value);
                    form.reset();
                    scrollToBottom();
                }
                catch (err)
                {
                    console.error(err);
                }
            }
            
            // try {
            //     await fetch(form.action, {
            //         method: 'POST',
            //         body: formData
            //     });
                
            //     form.reset();
            //     scrollToBottom();
            // } catch (error) {
            //     console.error('Error:', error);
            // }
        });

        function scrollToBottom() {
            const container = document.getElementById('messagesContainer');
            if (container) {
                container.scrollTop = container.scrollHeight;
            }
        }

        // При загрузке страницы прокручиваем вниз
        document.addEventListener('DOMContentLoaded', scrollToBottom);
    </script>
}

Pages/User/Projects.cshtml
@page
@model final_qualifying_work.Pages.User.ProjectsModel

@{
    ViewData["Title"] = "Проекты";
}

<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>@ViewData["Title"]</h1>
        @if (true)
        {
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#createProjectModal">
                <i class="bi bi-plus-circle"></i> Создать проект
            </button>
        }
    </div>

    @if (Model.Projects.Any())
    {
        <div class="row">
            @foreach (var project in Model.Projects)
            {
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        @* @if (!string.IsNullOrEmpty(project.ImageUrl))
                {
                <img src="@project.ImageUrl" class="card-img-top" alt="@project.Title">
                } *@
                        <div class="card-body">
                            <h5 class="card-title">@project.Title</h5>
                            <p class="card-text">@project.Description</p>
                            <div class="text-muted small mb-3">
                                Добавлено: @project.CreatedDate.ToShortDateString()
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="/User/Tasks?projectId=@project.Id" class="btn btn-primary">
                                Открыть проект
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <div class="alert alert-info">
            В данный момент нет доступных проектов. Зайдите позже!
        </div>
    }
    <!-- Модальное окно создания проекта -->
    <div class="modal fade" id="createProjectModal" tabindex="-1" aria-labelledby="createProjectModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createProjectModalLabel">Создать новый проект</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" asp-page-handler="Create" enctype="multipart/form-data">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="projectTitle" class="form-label">Название проекта</label>
                            <input type="text" class="form-control" id="projectTitle" name="Title" required>
                        </div>
                        <div class="mb-3">
                            <label for="projectDescription" class="form-label">Описание</label>
                            <textarea class="form-control" id="projectDescription" name="Description" rows="3"></textarea>
                        </div>
                        @* <div class="mb-3">
                            <label for="projectUrl" class="form-label">Ссылка на проект</label>
                            <input type="url" class="form-control" id="projectUrl" name="ProjectUrl">
                        </div>
                        <div class="mb-3">
                            <label for="projectImage" class="form-label">Изображение проекта</label>
                            <input type="file" class="form-control" id="projectImage" name="ImageFile" accept="image/*">
                        </div>
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="projectPublished" name="IsPublished" checked>
                            <label class="form-check-label" for="projectPublished">Опубликовать сразу</label>
                        </div> *@
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-success">Создать проект</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // При клике на проект сохраняем ID в localStorage
        document.querySelectorAll('.card-footer a').forEach(link => {
            link.addEventListener('click', function () {
                const projectId = new URL(this.href).searchParams.get('Id');
                localStorage.setItem('currentProjectId', projectId);
            });
        });
    </script>
    <partial name="_ValidationScriptsPartial" />
    <script>
        // Обработка успешного создания проекта
        document.addEventListener('DOMContentLoaded', function () {
            const createForm = document.querySelector('form[asp-page-handler="Create"]');
            if (createForm) {
                createForm.addEventListener('submit', function (e) {
                    e.preventDefault();

                    const formData = new FormData(this);

                    fetch('?handler=Create', {
                        method: 'POST',
                        body: formData,
                        headers: {
                            'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value
                        }
                    })
                        .then(response => {
                            if (!response.ok) {
                                return response.json().then(err => { throw new Error(err.error); });
                            }
                            return response.json();
                        })
                        .then(data => {
                            if (data.success) {
                                // Закрываем модальное окно
                                const modal = bootstrap.Modal.getInstance(document.getElementById('createProjectModal'));
                                modal.hide();

                                // Обновляем страницу
                                window.location.reload();
                            } else {
                                alert(data.message || 'Ошибка при создании проекта');
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                            alert(error.message);
                        });
                });
            }
        });
    </script>
}